name: brutal-nginx CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      #NGINX_VERSION: nginx-1.27.4
      NGINX_VERSION: nginx

    steps:
    - uses: actions/checkout@v3
    #- name: download nginx
      #working-directory: ../
      #run: wget https://nginx.org/download/${{env.NGINX_VERSION}}.tar.gz
    #- name: uncompress nginx
      #working-directory: ../
      #run: tar zxvf ${{env.NGINX_VERSION}}.tar.gz
    - name: Git Clone Action
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: nginx/nginx
    - name: configure (build as a dynamic module)
      working-directory: ../${{env.NGINX_VERSION}}
      run: ./configure --with-compat --add-dynamic-module=../brutal-nginx
    - name: make
      working-directory: ../${{env.NGINX_VERSION}}
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ngx_http_tcp_brutal_module.so
        path: /home/runner/work/brutal-nginx/${{env.NGINX_VERSION}}/objs/ngx_http_tcp_brutal_module.so
    - name: remove
      working-directory: ../
      run: rm -rf "${{env.NGINX_VERSION}}*"
    
          
